use std::fs;
use std::path::PathBuf;

fn main() {
    // Tauri's `generate_context!` macro validates the `frontendDist` path
    // at compile time (currently `../frontend/dist`). On a fresh checkout
    // that directory does not exist until the dev runs
    // `pnpm --filter ./frontend build` (or `just dev`, which calls Vite's
    // dev server via `beforeDevCommand`).
    //
    // For `cargo build --workspace` to succeed from a clean clone, this
    // build script ensures `../frontend/dist/index.html` exists with a
    // minimal stub. The real dist gets generated by Vite when the
    // developer actually runs the app; this stub is only there to satisfy
    // the macro check during plain `cargo build`.
    //
    // The stub file is in a gitignored directory (`frontend/dist`), so it
    // never pollutes the repo. It gets overwritten by `vite build`.
    //
    // Rationale committed at T0-12 per docs/MASTER_PLAN.md.
    ensure_frontend_dist_stub();

    tauri_build::build()
}

fn ensure_frontend_dist_stub() {
    let manifest_dir =
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
    let dist = PathBuf::from(&manifest_dir)
        .join("..")
        .join("frontend")
        .join("dist");
    if dist.join("index.html").exists() {
        return; // Real (or prior-stub) dist already in place.
    }
    if let Err(err) = fs::create_dir_all(&dist) {
        // Non-fatal — let tauri_build emit the actual error if the dir is
        // unreachable.
        eprintln!("cargo:warning=failed to create {}: {err}", dist.display());
        return;
    }
    let stub = "<!doctype html>\n<html lang=\"en\">\n<head><meta charset=\"utf-8\"><title>Final Whistle</title></head>\n<body><div id=\"root\">stub dist - run `pnpm --filter ./frontend build` for the real bundle</div></body>\n</html>\n";
    if let Err(err) = fs::write(dist.join("index.html"), stub) {
        eprintln!(
            "cargo:warning=failed to write {}/index.html: {err}",
            dist.display()
        );
    }
    println!("cargo:rerun-if-changed=../frontend/dist");
}
